require 'slack-ruby-bot'
require 'slack-ruby-client'
require 'slack-referbot/commands/vacancylist'
require 'slack-referbot/commands/referral'
require 'slack-referbot/commands/abort'
require 'slack-referbot/commands/test'
require 'slack-referbot/bot'
