require 'slack-ruby-bot'
require 'slack-ruby-client'
require 'slack-referbot/commands/vacancylist'
require 'slack-referbot/commands/referral'
require 'slack-referbot/commands/phone'
require 'slack-referbot/commands/email'
require 'slack-referbot/bot'
require 'slack-referbot/commands/help'
